### ISSUE TITLE
required fields for logfmt

### ISSUE THREAD

**Issue by pohly** [aybabtme/humanlog#18]
From the main README.md I got the impression that humanlog can handle arbitrary logfmt data ("If you emit logs in JSON or in logfmt, you will enjoy pretty logs..."), and then I wondered why it left some simple logs completely unchanged, like:
```
msg=hello
```

After diving into the source I found that a log entry must have a `level`, `time`, and `msg` field (https://github.com/aybabtme/humanlog/blob/master/logrus_handler.go#L39). It would be useful to mention this.

About the implementation:
* "lvl" and "message" seem to be treated as aliases, but the sanity check doesn't include them, so I'm not sure whether those aliases really work?
* the check expects "msg" to be quoted. This is too strict, for example the go-logfmt/logfmt Encoder doesn't put quotation marks around values unless absolutely necessary.

**Comment by aybabtme** [comment]
Hi @pohly, thanks for this other issue. You're right, this behavior isn't consistent and could be made better. If you have a PR that adapts the software to fit you need, I'll be happy to merge it. Recently (aside for the ANSI color stuff) I let the project be guided by user submissions. The tool works fine for my need, and as long as things aren't broken by a PR, I'll merge whatever you send me. =)
