### ISSUE TITLE
use github.com/go-logfmt/logfmt

### ISSUE THREAD

**Issue by pohly** [aybabtme/humanlog#19]
When I throw some log at humanlog, it fails with a runtime panic in the parser.

I can't share the log and before I try to narrow it down further let me first ask whether it would make more sense to replace the builtin parser with https://github.com/go-logfmt/logfmt?

**Comment by aybabtme** [comment]
Yup it would make sense to use that package. Mine is hacked together.

At a minimum tho to fix this otherwise, I'd need a stacktrace and a reproducer.

**Comment by pohly** [comment]
Antoine Grondin <notifications@github.com> writes:
> Yup it would make sense to use that package. Mine is hacked together.
>
> At a minimum tho to fix this otherwise, I'd need a stacktrace and a reproducer.

Yes, of course. But I think it'll be easier to just give logfmt a
try. I might have a look...

**Comment by pohly** [comment]
I got a bit disenchanted with logfmt - probably I'll stick with plain text formatting in debug mode and JSON in production.

So don't expect any patches from about logfmt in humanlog anytime soon. I also can't reproduce the crash, so let's treat this issue as a feature request to move to go-logfmt/logfmt.

**Comment by aybabtme** [comment]
fixed by #28
