### ISSUE TITLE
Output appears unchanged... perhaps a setup issue on my end?

### ISSUE THREAD

**Issue by stephanbaker** [aybabtme/humanlog#2]
I'm working to make better use of structured logging, and came across your humanlog utility.  
**Operating System**: OSX
**Terminal Client**: Bash/Default

I have a small test log I created using [**gokit**](https://github.com/go-kit/kit/tree/master/log).  
`{"caller":"main.go:25","level":"debug","msg":"Testing Debug","service":"logtestapp","ts":"2016-07-21T19:50:18Z"}
{"caller":"main.go:26","level":"info","msg":"Testing Info","service":"logtestapp","ts":"2016-07-21T19:50:18Z"}
{"caller":"main.go:27","level":"warn","msg":"Testing Warn","service":"logtestapp","ts":"2016-07-21T19:50:18Z"}
{"caller":"main.go:28","level":"error","msg":"Testing Error","service":"logtestapp","ts":"2016-07-21T19:50:18Z"}
{"caller":"main.go:29","level":"crit","msg":"Testing Crit","service":"logtestapp","ts":"2016-07-21T19:50:18Z"}`

I installed **humanlog** using the **go get** method from your README.
`go get -u github.com/aybabtme/humanlog/...`

Once installed, I run the following command, but am not seeing any change to display of the logs I'm providing, save for the **humanlog> reading stdin...** at the top of the ouput.  
`humanlog < logtestapp.log `

Is there something I'm missing, or a potential misconfiguration I've encountered?  Anything that can point me in the right direction would be greatly appreciated, thanks!

**Comment by aybabtme** [comment]
Hi @stephanbaker! Right now `humanlog` is detecting JSON logs that have the following fields:
```
{"time":..., "level": ..., "msg": ...}
```
gokit uses the `"ts"` field instead of `"time"`, so it's not detected by `humanlog` as being structured logs. It should be an easy fix to make it support `"ts"` also, if you want to give it a shot!

**Comment by stephanbaker** [comment]
That makes sense, I should have dived in a bit more.  After making the corresponding changes on my end, the tool is working as expected.  Thanks for the help.  Enjoying humanlog so far!

**Comment by aybabtme** [comment]
@stephanbaker glad to hear! Did you improve `humanlog` to support `ts`? If so, would you mind firing a PR this way, that'd be useful!

**Comment by stephanbaker** [comment]
I took the path of least resistance and updated my log output to match the expected `time` key.  If I do add that support to `humanlog` though I'll be sure to send that pull request your way.  How do you feel about adding it as a flag to override the default `ts` key?

**Comment by aybabtme** [comment]
@stephanbaker so usually I don't like magic, but in `humanlog`'s case i like it to just 'work' =P a flag wouldn't be 'just work' so I'd prefer something that discovers its a log that looks like it was made by go-kit.
