### ISSUE TITLE
Consider using GoReleaser

### ISSUE THREAD

**Issue by zet4** [aybabtme/humanlog#7]
As title says, I suggest you guys start using travis-ci with [GoReleaser](https://github.com/goreleaser/releaser), it lets you cross build binaries to your releases.

**Comment by aybabtme** [comment]
Great idea, I didn't know about this! Looks pretty interesting!

**Comment by aybabtme** [comment]
@zet4 I've integrated `GoReleaser` in the release script, thanks for the suggestion!
